# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9242a6e7aea82e0d0110504e5e41afbd6722a7381161d44f46dada64a8634bcf9efa3889d179b59c484905450c92d2c40d50d64ce001d91253dc955b11eb10ef
  advanon_app_id: dedf9f9110c53117e89bba9c77a99a7e2e20ab66ab5c2a4d2ac53ecf6b79b7e7
  advanon_secret: 198b4cdf31ec6f50fc6d25d6bcdd5a9e541b6a8978fedfbb5c7fc4b25a0672b5
  # Change above advanon_app_id and advanon_secret to the values you received after creating an authenticated app


test:
  secret_key_base: 426baec424d60d8a84b9a7619b450a7e62decb57541c3b137b2700d3731e1cb1df8313fdd64e91e94224ec645c06dc58f8ad6b9a5cf05581706ac18d3c736104

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
